#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border Setup
bspc config border_width	4
bspc config focused_border_color	"#93518B"
bspc config active_border_color		"#5F4A65"
bspc config normal_border_color 	"#5F4A65"

# Padding
bspc config top_padding 	50
bspc config bottom_padding 	10
bspc config left_padding 	10
bspc config right_padding 	10

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
~/.config/bspwm/autostart.sh
~/.config/bspwm/utils.sh
